### PR TITLE
IPLAYER-45548: Replace cache key package version with schema version

### PR DESCRIPTION
**Pull request by cjewell47**
## Description

Right now HTTP-Transport-Cache includes the package version number in its key. This means for changes where there is no change to the data stored - e.g. readme changes, we are diluting the cache for where that version is updated. To fix this we have replaced the package version with a config value that we can update when we actually make a data change

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] ~New feature (non-breaking change which adds functionality)~
- [ ] ~Breaking change (fix or feature that would cause existing functionality to change)~
## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] ~I have added tests to cover my changes.~
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by drrobharper — COMMENTED** [review]
I think I disagree with replacing the user-agent in the key with anything. We are caching responses, which are completely unrelated to the code used to make the requests or cache them.

**Review by chr15stevens — COMMENTED** [review]
I'd argue against this change tbh. I think in some ways that you aren't addressing the core issue of people not bumping consumers when they make an update.

The same thing will happen with this change. They'll make a change, increment the new config version and then not update it everywhere.

**Comment by chr15stevens** [comment]
> We can never bump a dependency everywhere all at once, so if the user-agent/rest-client version is left in the cache key the cache will always become fragmented for a period of time. I just don't see what purpose it serves. The only reason you would want to add something into the cache key is for a breaking change to how objects are stored in the cache. IMHO if there was a requirement to do that we could deal with that at the time

That's fair. But you will still get the fragmentation when you do introduce a breaking change and bump the version. You are also running the risk that if you miss bumping the config value then you will break stuff. Right now that's not possible to do as the version is incremented automatically.

I believe it would be easier/better to instil a culture of bumping dependencies everywhere than remembering minutiae like this change means.

**Review by drrobharper — APPROVED** [review]
Potential addition to the README but otherwise LGTM

**Review by JohnNewman1 — APPROVED** [review]

**Pull request merged**
